spring:
  application.name: spring-boot-with-mapp-struct
  datasource:
    url: jdbc:h2:mem:ecommerceDB
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    context-path: /ecommerce